// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lobby.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result int32

const (
	Result_REGISTER_SUCCESS Result = 0
	Result_REGISTER_FAIL    Result = 1
	Result_LOGIN_SUCCESS    Result = 2
	Result_LOGIN_FAIL       Result = 3
)

var Result_name = map[int32]string{
	0: "REGISTER_SUCCESS",
	1: "REGISTER_FAIL",
	2: "LOGIN_SUCCESS",
	3: "LOGIN_FAIL",
}

var Result_value = map[string]int32{
	"REGISTER_SUCCESS": 0,
	"REGISTER_FAIL":    1,
	"LOGIN_SUCCESS":    2,
	"LOGIN_FAIL":       3,
}

func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}

func (Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5f0edfb21975fe5, []int{0}
}

// 用户登陆协议
type UserLogin struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=LoginName,proto3" json:"LoginName,omitempty"`
	LoginPW              string   `protobuf:"bytes,2,opt,name=LoginPW,proto3" json:"LoginPW,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogin) Reset()         { *m = UserLogin{} }
func (m *UserLogin) String() string { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()    {}
func (*UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0edfb21975fe5, []int{0}
}

func (m *UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogin.Unmarshal(m, b)
}
func (m *UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogin.Marshal(b, m, deterministic)
}
func (m *UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogin.Merge(m, src)
}
func (m *UserLogin) XXX_Size() int {
	return xxx_messageInfo_UserLogin.Size(m)
}
func (m *UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogin proto.InternalMessageInfo

func (m *UserLogin) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserLogin) GetLoginPW() string {
	if m != nil {
		return m.LoginPW
	}
	return ""
}

type UserLogin_Result struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogin_Result) Reset()         { *m = UserLogin_Result{} }
func (m *UserLogin_Result) String() string { return proto.CompactTextString(m) }
func (*UserLogin_Result) ProtoMessage()    {}
func (*UserLogin_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0edfb21975fe5, []int{0, 0}
}

func (m *UserLogin_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogin_Result.Unmarshal(m, b)
}
func (m *UserLogin_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogin_Result.Marshal(b, m, deterministic)
}
func (m *UserLogin_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogin_Result.Merge(m, src)
}
func (m *UserLogin_Result) XXX_Size() int {
	return xxx_messageInfo_UserLogin_Result.Size(m)
}
func (m *UserLogin_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogin_Result.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogin_Result proto.InternalMessageInfo

func (m *UserLogin_Result) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 注册协议
type UserRegister struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=LoginName,proto3" json:"LoginName,omitempty"`
	LoginPW              string   `protobuf:"bytes,2,opt,name=LoginPW,proto3" json:"LoginPW,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegister) Reset()         { *m = UserRegister{} }
func (m *UserRegister) String() string { return proto.CompactTextString(m) }
func (*UserRegister) ProtoMessage()    {}
func (*UserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0edfb21975fe5, []int{1}
}

func (m *UserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegister.Unmarshal(m, b)
}
func (m *UserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegister.Marshal(b, m, deterministic)
}
func (m *UserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegister.Merge(m, src)
}
func (m *UserRegister) XXX_Size() int {
	return xxx_messageInfo_UserRegister.Size(m)
}
func (m *UserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegister proto.InternalMessageInfo

func (m *UserRegister) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserRegister) GetLoginPW() string {
	if m != nil {
		return m.LoginPW
	}
	return ""
}

// 消息返回协议
type UserResult struct {
	RetResult            Result   `protobuf:"varint,1,opt,name=RetResult,proto3,enum=msg.Result" json:"RetResult,omitempty"`
	ErrorInfo            string   `protobuf:"bytes,2,opt,name=ErrorInfo,proto3" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResult) Reset()         { *m = UserResult{} }
func (m *UserResult) String() string { return proto.CompactTextString(m) }
func (*UserResult) ProtoMessage()    {}
func (*UserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0edfb21975fe5, []int{2}
}

func (m *UserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResult.Unmarshal(m, b)
}
func (m *UserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResult.Marshal(b, m, deterministic)
}
func (m *UserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResult.Merge(m, src)
}
func (m *UserResult) XXX_Size() int {
	return xxx_messageInfo_UserResult.Size(m)
}
func (m *UserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResult.DiscardUnknown(m)
}

var xxx_messageInfo_UserResult proto.InternalMessageInfo

func (m *UserResult) GetRetResult() Result {
	if m != nil {
		return m.RetResult
	}
	return Result_REGISTER_SUCCESS
}

func (m *UserResult) GetErrorInfo() string {
	if m != nil {
		return m.ErrorInfo
	}
	return ""
}

// 玩家有角色的情况
type UserST struct {
	UID                  string   `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	ServerID             string   `protobuf:"bytes,2,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	RoleUID              string   `protobuf:"bytes,3,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`
	RoleName             string   `protobuf:"bytes,4,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	RoleLev              string   `protobuf:"bytes,5,opt,name=RoleLev,proto3" json:"RoleLev,omitempty"`
	Coin                 string   `protobuf:"bytes,6,opt,name=Coin,proto3" json:"Coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserST) Reset()         { *m = UserST{} }
func (m *UserST) String() string { return proto.CompactTextString(m) }
func (*UserST) ProtoMessage()    {}
func (*UserST) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f0edfb21975fe5, []int{3}
}

func (m *UserST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserST.Unmarshal(m, b)
}
func (m *UserST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserST.Marshal(b, m, deterministic)
}
func (m *UserST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserST.Merge(m, src)
}
func (m *UserST) XXX_Size() int {
	return xxx_messageInfo_UserST.Size(m)
}
func (m *UserST) XXX_DiscardUnknown() {
	xxx_messageInfo_UserST.DiscardUnknown(m)
}

var xxx_messageInfo_UserST proto.InternalMessageInfo

func (m *UserST) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *UserST) GetServerID() string {
	if m != nil {
		return m.ServerID
	}
	return ""
}

func (m *UserST) GetRoleUID() string {
	if m != nil {
		return m.RoleUID
	}
	return ""
}

func (m *UserST) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UserST) GetRoleLev() string {
	if m != nil {
		return m.RoleLev
	}
	return ""
}

func (m *UserST) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func init() {
	proto.RegisterEnum("msg.Result", Result_name, Result_value)
	proto.RegisterType((*UserLogin)(nil), "msg.UserLogin")
	proto.RegisterType((*UserLogin_Result)(nil), "msg.UserLogin.Result")
	proto.RegisterType((*UserRegister)(nil), "msg.UserRegister")
	proto.RegisterType((*UserResult)(nil), "msg.UserResult")
	proto.RegisterType((*UserST)(nil), "msg.UserST")
}

func init() { proto.RegisterFile("lobby.proto", fileDescriptor_a5f0edfb21975fe5) }

var fileDescriptor_a5f0edfb21975fe5 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x4f, 0xbb, 0x40,
	0x14, 0xfc, 0x51, 0x5a, 0x7e, 0xf2, 0xaa, 0x0d, 0x6e, 0x3c, 0x90, 0xc6, 0x18, 0xc3, 0x49, 0x3d,
	0xf4, 0xa0, 0x9f, 0xc0, 0x50, 0xda, 0x6c, 0x42, 0xaa, 0xd9, 0x85, 0x78, 0x34, 0x62, 0x9e, 0x84,
	0x08, 0xac, 0x59, 0x90, 0xc4, 0xaf, 0xe2, 0xa7, 0x35, 0xbb, 0xcb, 0x1f, 0xcf, 0xde, 0x66, 0xe6,
	0xbd, 0x99, 0x79, 0x90, 0x85, 0x65, 0x29, 0xb2, 0xec, 0x6b, 0xf3, 0x21, 0x45, 0x2b, 0x88, 0x5d,
	0x35, 0x79, 0xf0, 0x0a, 0x6e, 0xda, 0xa0, 0x8c, 0x45, 0x5e, 0xd4, 0xe4, 0x1c, 0x5c, 0x0d, 0x0e,
	0x2f, 0x15, 0xfa, 0xd6, 0xa5, 0x75, 0xe5, 0xb2, 0x49, 0x20, 0x3e, 0xfc, 0xd7, 0xe4, 0xf1, 0xc9,
	0x9f, 0xe9, 0xd9, 0x40, 0xd7, 0x17, 0xe0, 0x30, 0x6c, 0x3e, 0xcb, 0x96, 0x9c, 0xc1, 0xa2, 0x15,
	0xef, 0x58, 0xf7, 0x6e, 0x43, 0x82, 0x1d, 0x1c, 0xab, 0x12, 0x86, 0x79, 0xd1, 0xb4, 0x28, 0xff,
	0xda, 0x13, 0xa4, 0x00, 0x26, 0x47, 0x77, 0x5d, 0x83, 0xcb, 0xb0, 0x35, 0x44, 0xa7, 0xac, 0x6e,
	0x97, 0x9b, 0xaa, 0xc9, 0x37, 0x46, 0x62, 0xd3, 0x54, 0x15, 0x46, 0x52, 0x0a, 0x49, 0xeb, 0x37,
	0xd1, 0x87, 0x4e, 0x42, 0xf0, 0x6d, 0x81, 0xa3, 0x72, 0x79, 0x42, 0x3c, 0xb0, 0x53, 0xba, 0xed,
	0x6f, 0x52, 0x90, 0xac, 0xe1, 0x88, 0xa3, 0xec, 0x50, 0xd2, 0x6d, 0xef, 0x1c, 0xb9, 0xba, 0x94,
	0x89, 0x12, 0x95, 0xc3, 0x36, 0x97, 0xf6, 0x54, 0xb9, 0x14, 0xd4, 0x1f, 0x38, 0x37, 0xae, 0x81,
	0x0f, 0xae, 0x18, 0x3b, 0x7f, 0x31, 0xb9, 0x62, 0xec, 0x08, 0x81, 0x79, 0x28, 0x8a, 0xda, 0x77,
	0xb4, 0xac, 0xf1, 0x4d, 0xf2, 0xeb, 0xdf, 0x7a, 0x2c, 0xda, 0x53, 0x9e, 0x44, 0xec, 0x99, 0xa7,
	0x61, 0x18, 0x71, 0xee, 0xfd, 0x23, 0xa7, 0x70, 0x32, 0xaa, 0xbb, 0x7b, 0x1a, 0x7b, 0x96, 0x92,
	0xe2, 0x87, 0x3d, 0x3d, 0x8c, 0x5b, 0x33, 0xb2, 0x02, 0x30, 0x92, 0x5e, 0xb1, 0x33, 0x47, 0x3f,
	0x81, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x45, 0x51, 0xf8, 0x11, 0x02, 0x00, 0x00,
}
